### ISSUE TITLE
cyton_gamma_1500.launch is not a launch file in package

### ISSUE THREAD

**Issue by mortimer92** [GertKanter/cyton_gamma_1500_description#1]
Hello!
I have an issue with the launching of the cyton_gamma_1500_description.
  Following the installation steps from "http://wiki.ros.org/cyton_gamma_1500_description ", I cannot launch using : "roslaunch cyton_gamma_1500_description cyton_gamma_1500.launch" without getting this error message:

 [cyton_gamma_1500.launch] is neither a launch file in package [cyton_gamma_1500_description] nor is [cyton_gamma_1500_description] a launch file name
The traceback for the exception was written to the log file

I have joint_state_publisher, robot_state_publisher and rviz installed, but this doesn't seem to be the problem i think, otherwise the console would've told me that i have some dependecies missing and I state that the installation was without any issues (I don't know if I'm using the correct words here and I apologise for that).

**Comment by GertKanter** [comment]
Hello!

Can you do "roscd cyton_gamma_1500_description" without an error? If you
can't, then it is likely that the cyton_gamma_1500_description is not in
the ROS package path. Run "source <your_catkin_ws>/devel/setup.bash" and
try again. See more at
http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment

2015-03-10 21:24 GMT+02:00 mortimer92 notifications@github.com:

**Comment by mortimer92** [comment]
Thank you very much! Up and running
